---

- name: install deps
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-dev
      - python-pip
    update_cache: yes
    cache_valid_time: 3600

- name: add docker repo key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt entry
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes
    state: present

- name: install docker
  apt:
    name: docker-ce
    state: present
  notify: start docker

- name: upgrade pip, install docker-py and docker compose
  pip:
    name:
      - pip
      - docker
      - docker-compose
    state: present
